

[log]
# log format encoder, see https://docs.rs/log4rs/1.2.0/log4rs/append/file/struct.FileAppenderDeserializer.html#configuration
# for more information
encoder = "{d}:{l} - {m}{n}"

# log level
level = "info"

# will delete and regenerate log file if exceeded the limit, unit is MB
limit = 10


[crates]
# download index from domain
index_domain = "https://github.com/rust-lang/crates.io-index.git"

# download crates from domain
domain = "https://static.crates.io/crates"

# Number of download threads
download_threads = 2

# when local file does not exist, redirect client to this domain
redirect_domain = "https://rsproxy.cn"

# when local file does not exist, will try to download from these doamins
backup_domain = ["https://static.crates.io/crates", "https://rsproxy.cn/crates"]

[rustup]
# download rustup from domain
domain = "https://static.rust-lang.org"

# Number of download threads
download_threads = 8

# stable version that you want to keep forever
sync_stable_versions = [
    "1.0",
    "1.1",
    "1.2",
    "1.3",
    "1.4",
    "1.5",
    "1.6",
    "1.7",
    "1.8",
    "1.9",
    "1.10",
    "1.11",
    "1.12",
    "1.12.1",
    "1.13",
    "1.14",
    "1.15",
    "1.15.1",
    "1.16",
    "1.17",
    "1.18",
    "1.19",
    "1.20",
    "1.21",
    "1.22",
    "1.22.1",
    "1.23",
    "1.24",
    "1.24.1",
    "1.25",
    "1.26",
    "1.26.1",
    "1.26.2",
    "1.27",
    "1.27.1",
    "1.27.2",
    "1.28",
    "1.29",
    "1.29.1",
    "1.29.2",
    "1.30",
    "1.30.1",
    "1.31",
    "1.31.1",
    "1.32",
    "1.33",
    "1.34",
    "1.34.1",
    "1.34.2",
    "1.35",
    "1.36",
    "1.37",
    "1.38",
    "1.39",
    "1.40",
    "1.41",
    "1.41.1",
    "1.42",
    "1.43",
    "1.43.1",
    "1.44",
    "1.44.1",
    "1.45",
    "1.45.1",
    "1.45.2",
    "1.46",
    "1.47",
    "1.48",
    "1.49",
    "1.50",
    "1.51",
    "1.52",
    "1.52.1",
    "1.53",
    "1.54",
    "1.55",
    "1.56",
    "1.56.1",
    "1.57",
    "1.58",
    "1.58.1",
    "1.59",
    "1.60",
    "1.61",
    "1.62",
    "1.62.1",
    "1.63",
    "1.64",
    "1.65",
]

# days you want to keep for historical nightly version
sync_nightly_days = 30

# days you want to keep for historical beta version
sync_beta_days = 30





